on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Check Nix targets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main # This action
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Check nix flake
        run: nix flake check
